# Generated by Django 5.2.1 on 2026-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='confidence_level',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Not confident'), (2, '2 - Slightly confident'), (3, '3 - Moderately confident'), (4, '4 - Very confident'), (5, '5 - Extremely confident')], null=True),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='formal_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='frequency_use',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely')], max_length=10),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='years_of_experience',
            field=models.IntegerField(blank=True, choices=[(0, 'Less than 1 year'), (1, '1-2 years'), (2, '3-5 years'), (3, '6-10 years'), (4, 'More than 10 years')], null=True),
        ),
    ]
