# Generated by Django 5.2.1 on 2026-07-17 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skillassessment_confidence_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillassessment',
            name='proficiency',
            field=models.IntegerField(default=0, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Proficiency Level (%)'),
        ),
    ]
