# Generated by Django 5.2.1 on 2026-06-17 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $50,000 - $80,000', max_length=100)),
            ],
            options={
                'verbose_name': 'Career Path',
                'verbose_name_plural': 'Career Paths',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('leadership', 'Leadership'), ('creative', 'Creative'), ('business', 'Business'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_gap', models.JSONField(help_text='Dictionary of skill names and gap scores')),
                ('roadmap', models.JSONField(help_text='3-month learning roadmap as JSON')),
                ('career_readiness_score', models.IntegerField(help_text='Score from 0 to 100 indicating readiness for recommended career')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
                ('recommended_career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_recommendations', to='ai.careerpath')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='careerpath',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='career_paths', to='ai.skill'),
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score from 0 to 100')),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert'), (5, 'Master')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ai.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill Assessment',
                'verbose_name_plural': 'Skill Assessments',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
